socialapp/account/urls.py
from re import template
from telnetlib import LOGOUT
from unicodedata import name
from django.contrib import admin
from django.urls import URLPattern, path
from django.contrib.auth import views as auth_views
from account import views
from django.contrib.auth import get_user_model

app_name = 'account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('sigup/', views.signup.as_view(), name='signup')
]

socialapp/socialapp/urls.py
from argparse import Namespace
from tokenize import Name
from unicodedata import name
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('account/', include('account.urls', namespace='account')),
    path('account/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

socialapp/account/models.py
from django.db import models

# Create your models here.

socialapp/account/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserSingUpForms(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"

socialapp/account/views.py
from venv import create
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView
from . import forms
# Create your views here.


class signup(CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

socialapp/socialapp/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'

socialapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>social</title>
    <!-- Latest compiled and minified CSS -->
        
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
        
        
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
<body>

    <nav class="navbar mynav" role="navigation" id="navbar">
        <div class="contaner">
            <a class='navbar-brand mynav' href="{% url 'home' %}">social</a>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#">Post</a></li>
                    <li><a href="#">Group</a></li>
                    <li><a href="#">create Group</a></li>
                    <li><a href="{% url 'account:logout' %}">Log out</a></li>

                {% else %}
                    <li><a href="#">Groups</a></li>
                    <li><a href="{% url 'account:login' %}">Log IN</a></li>
                    <li><a href="{% url 'account:signup' %}">Sign up</a></li>
                {% endif %}



            </ul>
        </div>
    </nav>

    <div class="container my contant">
        {% block content %}
        <p>welcome</p>
        {% endblock %}
    </div>
    
</body>
</html>

socialapp/templates/index.html
{% extends "base.html" %}

{% block title %}


{% endblock %}